default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: elevate_development

test:
  <<: *default
  database: elevate_test

production:
  <<: *default
  database: elevate_production
  # username: elevate
  # password: <%= ENV['ELEVATE_DATABASE_PASSWORD'] %>
